const isNui = !!process.env.CLAUDE_CODE_NUI

export const CHECK    = isNui ? 'v'     : '✓'   // U+2713
export const CROSS    = isNui ? 'x'     : '✗'   // U+2717
export const WARN     = isNui ? '!'     : '⚠'   // U+26A0
export const ERROR_X  = isNui ? 'X'     : '❌'  // U+274C
export const STAR_AST = isNui ? '*'     : '✻'   // U+273B teardrop asterisk
export const HOOK     = isNui ? '|_'    : '⎿'   // U+23BF
export const TRI_R    = isNui ? '>'     : '▶'   // U+25B6
export const TRI_L    = isNui ? '<'     : '◀'   // U+25C0
export const DIAMOND  = isNui ? '<>'    : '◇'   // U+25C7
export const BULLET   = isNui ? '*'     : '●'   // U+25CF
export const SANDBOX  = isNui ? '#'     : '⧈'   // U+29C8
export const IDE_LINK = isNui ? '+'     : '⧉'   // U+29C9
export const RETURN   = isNui ? '<-'    : '⏎'   // U+23CE
export const STAR5    = isNui ? '*'     : '★'   // U+2605
export const BOT      = isNui ? '[bot]' : '🤖'  // U+1F916
export const OK_BOX   = isNui ? '[OK]'  : '✅'  // U+2705
export const CTX_BOX  = isNui ? '[]'    : '⛶'  // U+26F6
export const CTX_X    = isNui ? '[~]'   : '⛝'  // U+26DD
export const TRI_D    = isNui ? 'v'     : '▼'   // U+25BC
export const TRI_RS   = isNui ? '>'     : '▸'   // U+25B8
export const SPIN_STATIC = isNui ? '*'  : '✳'   // U+2733
export const TREE_END  = isNui ? '`-'  : '└'    // U+2514 box-drawing
export const TREE_MID  = isNui ? '|-'  : '├'    // U+251C box-drawing
export const ARROW_R   = isNui ? '->'  : '→'    // U+2192
export const ARROW_L   = isNui ? '<-'  : '←'    // U+2190
export const ARROW_U   = isNui ? '^'   : '↑'    // U+2191
export const ARROW_D   = isNui ? 'v'   : '↓'    // U+2193
export const HLINE     = isNui ? '-'   : '─'    // U+2500
export const TOP_LINE  = isNui ? '-'   : '▔'    // U+2594
export const PROMPT_R  = isNui ? '>'   : '❯'    // U+276F
